// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4UKWsAMfUC1kEuLgBvknC
// Component: yQAII8_kvyW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_zendrop.module.css"; // plasmic-import: 4UKWsAMfUC1kEuLgBvknC/projectcss
import sty from "./PlasmicValueStack4.module.css"; // plasmic-import: yQAII8_kvyW/css

createPlasmicElementProxy;

export type PlasmicValueStack4__VariantMembers = {};
export type PlasmicValueStack4__VariantsArgs = {};
type VariantPropType = keyof PlasmicValueStack4__VariantsArgs;
export const PlasmicValueStack4__VariantProps = new Array<VariantPropType>();

export type PlasmicValueStack4__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
};
type ArgPropType = keyof PlasmicValueStack4__ArgsType;
export const PlasmicValueStack4__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3"
);

export type PlasmicValueStack4__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultValueStack4Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicValueStack4__RenderFunc(props: {
  variants: PlasmicValueStack4__VariantsArgs;
  args: PlasmicValueStack4__ArgsType;
  overrides: PlasmicValueStack4__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__zByFl)}>
        <div className={classNames(projectcss.all, sty.freeBox__pWlfL)}>
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__cfxRf)}>
              {true ? (
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__j5SGy)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                />
              ) : null}
            </div>
          ) : null}
          <div className={classNames(projectcss.all, sty.freeBox__i9YsC)}>
            <div className={classNames(projectcss.all, sty.freeBox___609U6)}>
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6W6N
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#636363" }}
                      >
                        {"30-Day Zendrop PLUS App Free Trial:"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.children,
                className: classNames(sty.slotTargetChildren)
              })}
            </div>
            {true ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zeGkJ
                )}
              >
                {"Enter some text"}
              </div>
            ) : null}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___6BfpT)}>
            <div className={classNames(projectcss.all, sty.freeBox__luToE)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__mIzMa)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/zendrop/images/downloadsvg2.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vYqIq
                )}
              >
                {"Instant Access"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___8Uogv)}>
            <div className={classNames(projectcss.all, sty.freeBox__yOh4K)}>
              <div className={classNames(projectcss.all, sty.freeBox___1A9Z6)}>
                {p.renderPlasmicSlot({
                  defaultContents: "Price: $2,997",
                  value: args.slot,
                  className: classNames(sty.slotTargetSlot)
                })}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___2Dug3)}>
            <p.PlasmicLink
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={"https://zendrop.com/checkout-trial-fb/" as const}
              platform={"nextjs"}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dkSh
                    )}
                  >
                    {"\ud83d\udc49  FREE  \ud83d\udc48"}
                  </div>
                ),
                value: args.slot2
              })}
            </p.PlasmicLink>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__fBnjc)}>
          <div className={classNames(projectcss.all, sty.freeBox__edqus)}>
            <div className={classNames(projectcss.all, sty.freeBox__ym0Wu)}>
              {p.renderPlasmicSlot({
                defaultContents:
                  "Network and learn from some of the top dropshippers on the planet. ",
                value: args.slot3
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicValueStack4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicValueStack4__VariantsArgs;
    args?: PlasmicValueStack4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicValueStack4__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicValueStack4__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicValueStack4__ArgProps,
          internalVariantPropNames: PlasmicValueStack4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicValueStack4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValueStack4";
  } else {
    func.displayName = `PlasmicValueStack4.${nodeName}`;
  }
  return func;
}

export const PlasmicValueStack4 = Object.assign(
  // Top-level PlasmicValueStack4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicValueStack4
    internalVariantProps: PlasmicValueStack4__VariantProps,
    internalArgProps: PlasmicValueStack4__ArgProps
  }
);

export default PlasmicValueStack4;
/* prettier-ignore-end */
